copy setup.sqf server /Y
copy setup.sqf server\func /Y
copy setup.sqf client /Y
copy setup.sqf client\func /Y
copy setup.sqf common /Y
copy setup.sqf common\BIS_Effects /Y
copy setup.sqf common\Cargo_Drop /Y
copy setup.sqf common\bon_ais /Y
copy setup.sqf dialogs /Y
copy setup.sqf dialogs\DomiLift /Y
copy setup.sqf dialogs\tele /Y
copy setup.sqf fsms /Y
copy macros.sqf server /Y
copy macros.sqf server\func /Y
copy macros.sqf client /Y
copy macros.sqf client\func /Y
copy macros.sqf common /Y
copy macros.sqf common\BIS_Effects /Y
copy macros.sqf common\Cargo_Drop /Y
copy macros.sqf common\bon_ais /Y
copy macros.sqf dialogs /Y
copy macros.sqf dialogs\DomiLift /Y
copy macros.sqf dialogs\tele /Y
copy macros.sqf fsms /Y